# Generated by Django 4.2.30 on 2026-07-11 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('visits_count', models.PositiveIntegerField(default=0)),
                ('selected_count', models.PositiveIntegerField(default=0)),
                ('last_visited_batch', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(db_index=True, max_length=255)),
                ('author', models.CharField(blank=True, help_text='Student name (optional)', max_length=255)),
                ('batch', models.CharField(db_index=True, help_text='e.g. 2025', max_length=20)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('verdict', models.CharField(choices=[('selected', 'Selected'), ('rejected', 'Rejected'), ('on_hold', 'On Hold'), ('internship', 'Internship Offer')], db_index=True, default='rejected', max_length=20)),
                ('overall_process_summary', models.TextField(blank=True)),
                ('round_1_name', models.CharField(blank=True, max_length=100)),
                ('round_1_topics', models.TextField(blank=True)),
                ('round_1_duration', models.CharField(blank=True, max_length=50)),
                ('round_1_notes', models.TextField(blank=True)),
                ('round_2_name', models.CharField(blank=True, max_length=100)),
                ('round_2_topics', models.TextField(blank=True)),
                ('round_2_duration', models.CharField(blank=True, max_length=50)),
                ('round_2_notes', models.TextField(blank=True)),
                ('round_3_name', models.CharField(blank=True, max_length=100)),
                ('round_3_topics', models.TextField(blank=True)),
                ('round_3_duration', models.CharField(blank=True, max_length=50)),
                ('round_3_notes', models.TextField(blank=True)),
                ('round_4_name', models.CharField(blank=True, max_length=100)),
                ('round_4_topics', models.TextField(blank=True)),
                ('round_4_duration', models.CharField(blank=True, max_length=50)),
                ('round_4_notes', models.TextField(blank=True)),
                ('round_5_name', models.CharField(blank=True, max_length=100)),
                ('round_5_topics', models.TextField(blank=True)),
                ('round_5_duration', models.CharField(blank=True, max_length=50)),
                ('round_5_notes', models.TextField(blank=True)),
                ('additional_rounds', models.TextField(blank=True)),
                ('tips_advice', models.TextField(blank=True)),
                ('ctc_offered', models.CharField(blank=True, max_length=100)),
                ('role_offered', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('student_submit', 'Student Submission'), ('admin_upload', 'Admin Upload (Excel)')], default='student_submit', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
