# Generated by Django 4.2.16 on 2026-07-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='students_appeared',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='students_appeared',
            field=models.PositiveIntegerField(default=0, help_text="Total students who appeared in this company's drive"),
        ),
    ]
