# Generated by Django 4.2.30 on 2026-07-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceChunk',
            fields=[
                ('chunk_id', models.AutoField(primary_key=True, serialize=False)),
                ('chunk_text', models.TextField()),
                ('chunk_type', models.CharField(choices=[('summary', 'Overall Summary'), ('round_1', 'Round 1'), ('round_2', 'Round 2'), ('round_3', 'Round 3'), ('round_4', 'Round 4'), ('round_5', 'Round 5'), ('tips', 'Tips & Advice')], max_length=20)),
                ('faiss_id', models.IntegerField(default=-1, help_text='FAISS internal integer id')),
                ('company', models.CharField(db_index=True, max_length=255)),
                ('batch', models.CharField(db_index=True, max_length=20)),
                ('verdict', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='experiences.experience')),
            ],
            options={
                'ordering': ['chunk_id'],
            },
        ),
    ]
